In [1]:
import torch
print(torch.__version__)

2.10.0+cu130


In [2]:
if torch.cuda.is_available():
    print("GPU is available. You can use GPU acceleration.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU.")

GPU is available. You can use GPU acceleration.
Using GPU: NVIDIA GeForce RTX 3060 Ti


# Creating a tensor

In [3]:
# Using empty
a = torch.empty(2, 3)
type(a)

torch.Tensor

In [4]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.rand(2, 3)

tensor([[0.1936, 0.2554, 0.2263],
        [0.4196, 0.0728, 0.1771]])

In [6]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [7]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
print("Using arrange ->", torch.arange(0, 10, 2))
print("Using linspace ->", torch.linspace(0, 10, 10))
print(torch.eye(5))
print(torch.full((3, 3), 7))

Using arrange -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


# Tensor Shapes

In [10]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)

torch.Size([2, 3])


In [11]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [14]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Tensor Data Types

In [15]:
x.dtype

torch.int64

In [16]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

# Math operations

In [17]:
x = torch.rand(2, 2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [18]:
x + 2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [19]:
x * 3

tensor([[0.6717, 0.9070],
        [0.5353, 2.4715]])

In [20]:
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

In [21]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [22]:
a + b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [23]:
c = torch.tensor([1, -2, 3, -4, 5])

In [24]:
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [25]:
torch.clamp(c, min=1, max=3)

tensor([1, 1, 3, 1, 3])

In [26]:
torch.median(c)

tensor(1)

# Matrix multiplication

In [27]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [28]:
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

# Inplace operations

In [29]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])
tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])


In [30]:
m.add_(n)

tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

In [31]:
m

tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

In [32]:
torch.relu(m)

tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

In [33]:
m.relu()

tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

# Copy

In [34]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a)
print(b)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [35]:
b = a.clone()
b

tensor([1, 2, 3])

# Tensor Operations on GPU

In [36]:
torch.cuda.is_available()

True

In [37]:
gpu = torch.device('cuda')

In [38]:
# Creating a new tensor on GPU
torch.rand(2, 3, device=gpu)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [39]:
# Moving an existing tensor to GPU
a = torch.rand(2, 3)
a

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]])

In [40]:
b = a.to(gpu)
b

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]], device='cuda:0')

In [41]:
b + 5 

tensor([[5.9053, 5.8356, 5.3039],
        [5.6726, 5.5740, 5.9233]], device='cuda:0')