In [23]:
import torch
print(torch.__version__)

2.10.0+cu130


In [24]:
if torch.cuda.is_available():
    print("GPU is available. You can use GPU acceleration.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU.")

GPU is available. You can use GPU acceleration.
Using GPU: NVIDIA GeForce RTX 3060 Ti


# Creating a tensor

In [25]:
# Using empty
a = torch.empty(2, 3)
type(a)

torch.Tensor

In [26]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [35]:
torch.rand(2, 3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [28]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [29]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [30]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
print("Using arrange ->", torch.arange(0, 10, 2))
print("Using linspace ->", torch.linspace(0, 10, 10))
print(torch.eye(5))
print(torch.full((3, 3), 7))

Using arrange -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])
